name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Permitir execução dos scripts do Maven Wrapper
        run: chmod +x mvnw

      - name: Build com Maven
        run: mvn clean package

      - name: Definir variáveis de ambiente sensíveis para o Maven
        run: |
          echo "jwt.secret=JvcyAJAjrd1ofcA+G6Sq/NcvmZdPfgafLj2uV2B/ZqU=" >> src/main/resources/application.properties
          echo "jwt.expiration=86400000" >> src/main/resources/application.properties
          echo "openai.api.url=https://api.openai.com/v1/chat/completions"  >> src/main/resources/application.properties
          echo "openai.model=gpt-4.1-nano"  >> src/main/resources/application.properties
          echo "openai.api.key=sk-proj-asdasdasdasdada"  >> src/main/resources/application.properties

      - name: Rodar testes
        run: mvn test --no-transfer-progress

      - name: Upload do artefato gerado
        uses: actions/upload-artifact@v4
        with:
          name: learnai-jar
          path: target/*.jar
