name: Java CI with Maven

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

env:
  MAVEN_OPTS: -Xmx2048m -Djava.security.egd=file:/dev/./urandom
  SPRING_PROFILES_ACTIVE: test  # Força uso do H2

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2
            target/
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Run unit tests with H2
        run: mvn -B clean test
        env:
          SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
          SPRING_DATASOURCE_USERNAME: sa
          SPRING_DATASOURCE_PASSWORD:

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-reports
          path: target/surefire-reports
          retention-days: 1

      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco
          retention-days: 1

      - name: Build JAR
        if: success()
        run: mvn -B package -DskipTests